gems: 
  - jekyll-paginate
  - jekyll-polyglot

exclude: ['LICENSE.md', 'README.md']

title:               Matheus Bratfisch
tagline:             'Cogito ergo sum'
url:                 
baseurl:             ''
paginate:            1
excerpt_separator:   '<!--more-->'
analytics:           'UA-5825966-12'

author:
  name:              Matheus Bratfisch
  url:               https://twitter.com/
  email:             matheusbrat@gmail.com
  description:       ''
  gravatar:          '60baed8344cc0d5b979b09c35042ede5'
  linkedin:          'https://www.linkedin.com/in/matheusbratfisch'
  contact:           
    github:          'https://github.com/x-warrior'
    twitter:         'https://twitter.com/matheusbrat'
    linkedin:        'https://www.linkedin.com/in/matheusbratfisch'

version:             1.0.0


languages: ["en", "pt_BR"]
default_lang: "en"
exclude_from_localization: ["public", "images", "css"]
parallel_localization: true
